# Generated by Django 3.2.6 on 2021-08-07 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('manager', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('manager_position', models.CharField(max_length=100, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания записи о компании')),
                ('date_edit', models.DateField(auto_now=True, verbose_name='Дата последнего изменения записи')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес компании')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=250, verbose_name='Проект')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('final_date', models.DateField(verbose_name='Дата окончания')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость проекта')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Введите номер телефона в формате "0XXXXXXXXX"', max_length=10, null=True, verbose_name='Телефон')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.CreateModel(
            name='CompanyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_email', models.EmailField(max_length=100, null=True, verbose_name='email')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компания')),
            ],
        ),
    ]
