# Generated by Django 3.2.6 on 2021-08-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210809_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(max_length=200, verbose_name='Адрес компании'),
        ),
    ]
